# Generated by Django 5.2.8 on 2026-05-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
