# Generated by Django 5.2.8 on 2026-05-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_bill_is_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category'),
        ),
    ]
