# Generated by Django 5.2.8 on 2026-05-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_bill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
