# Generated by Django 5.2.8 on 2026-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
